"""
DBA Metrics History Service - Store and retrieve historical metrics for trending

This service stores query performance metrics over time to enable:
- Baseline comparison for regression detection
- Trending analysis
- Capacity forecasting with real data
- Performance SLA tracking
"""
from typing import Optional, List, Dict, Any
from datetime import datetime, timedelta
from uuid import UUID
import json

from ....shared.logger import logger
from ....infrastructure.database_client import database_client
from ....shared.exceptions import DatabaseError


class DBAMetricsHistoryService:
    """
    Service for storing and retrieving DBA metrics history.
    
    Stores metrics in dba_metrics_history table for:
    - Query performance metrics
    - Wait statistics
    - I/O pressure readings
    - Capacity measurements
    """
    
    def __init__(self):
        """Initialize metrics history service"""
        self.db = database_client
    
    async def store_query_metric(
        self,
        connection_id: UUID,
        database_type: str,
        query_hash: str,
        mean_time_ms: float,
        max_time_ms: float,
        total_calls: int,
        rows_examined: Optional[int] = None,
        rows_returned: Optional[int] = None,
        metadata: Optional[Dict[str, Any]] = None,
        recorded_at: Optional[datetime] = None
    ) -> UUID:
        """
        Store query performance metric.
        
        Args:
            connection_id: Database connection ID
            database_type: Database type (PostgreSQL, MySQL, SQL Server)
            query_hash: Hash of the query
            mean_time_ms: Mean execution time in milliseconds
            max_time_ms: Max execution time in milliseconds
            total_calls: Total number of executions
            rows_examined: Number of rows examined
            rows_returned: Number of rows returned
            metadata: Optional metadata
            recorded_at: Timestamp (defaults to now)
            
        Returns:
            Metric ID (UUID)
            
        Raises:
            DatabaseError: If storage fails
        """
        try:
            pool = self.db.pool
            metric_id = UUID(int=0)  # Will be generated by DB
            recorded_at = recorded_at or datetime.utcnow()
            
            async with pool.acquire() as conn:
                row = await conn.fetchrow(
                    """
                    INSERT INTO dba_metrics_history (
                        connection_id, metric_type, database_type, query_hash,
                        mean_time_ms, max_time_ms, total_calls, rows_examined, rows_returned,
                        metadata, recorded_at
                    ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
                    RETURNING id
                    """,
                    connection_id,
                    "query_performance",
                    database_type,
                    query_hash,
                    mean_time_ms,
                    max_time_ms,
                    total_calls,
                    rows_examined,
                    rows_returned,
                    json.dumps(metadata or {}),
                    recorded_at,
                )
                
                if row:
                    metric_id = row["id"]
                    logger.info(
                        f"Stored query metric",
                        extra={
                            "metric_id": metric_id,
                            "connection_id": connection_id,
                            "query_hash": query_hash,
                            "mean_time_ms": mean_time_ms,
                        }
                    )
                
                return metric_id
                
        except Exception as e:
            logger.error(
                f"Failed to store query metric: {e}",
                extra={"connection_id": connection_id},
                exc_info=True
            )
            raise DatabaseError(f"Failed to store query metric: {e}") from e
    
    async def store_wait_stat_metric(
        self,
        connection_id: UUID,
        database_type: str,
        wait_type: str,
        wait_count: int,
        total_wait_ms: float,
        metadata: Optional[Dict[str, Any]] = None,
        recorded_at: Optional[datetime] = None
    ) -> UUID:
        """
        Store wait statistics metric.
        
        Args:
            connection_id: Database connection ID
            database_type: Database type
            wait_type: Type of wait event
            wait_count: Number of wait events
            total_wait_ms: Total wait time in milliseconds
            metadata: Optional metadata
            recorded_at: Timestamp (defaults to now)
            
        Returns:
            Metric ID (UUID)
        """
        try:
            pool = self.db.pool
            recorded_at = recorded_at or datetime.utcnow()
            
            async with pool.acquire() as conn:
                row = await conn.fetchrow(
                    """
                    INSERT INTO dba_metrics_history (
                        connection_id, metric_type, database_type, wait_type,
                        wait_count, total_wait_ms, metadata, recorded_at
                    ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
                    RETURNING id
                    """,
                    connection_id,
                    "wait_statistics",
                    database_type,
                    wait_type,
                    wait_count,
                    total_wait_ms,
                    json.dumps(metadata or {}),
                    recorded_at,
                )
                
                return row["id"] if row else None
                
        except Exception as e:
            logger.error(
                f"Failed to store wait stat metric: {e}",
                extra={"connection_id": connection_id},
                exc_info=True
            )
            raise DatabaseError(f"Failed to store wait stat metric: {e}") from e
    
    async def get_query_baseline(
        self,
        connection_id: UUID,
        query_hash: str,
        days: int = 7
    ) -> Optional[Dict[str, float]]:
        """
        Get baseline metrics for a query (average of last N days).
        
        Args:
            connection_id: Database connection ID
            query_hash: Query hash
            days: Number of days to look back
            
        Returns:
            Dict with baseline metrics (mean_time_ms, max_time_ms, total_calls)
        """
        try:
            pool = self.db.pool
            cutoff_date = datetime.utcnow() - timedelta(days=days)
            
            async with pool.acquire() as conn:
                row = await conn.fetchrow(
                    """
                    SELECT 
                        AVG(mean_time_ms) as avg_mean_time,
                        MAX(max_time_ms) as baseline_max_time,
                        AVG(total_calls) as avg_calls
                    FROM dba_metrics_history
                    WHERE connection_id = $1
                        AND query_hash = $2
                        AND metric_type = 'query_performance'
                        AND recorded_at >= $3
                    """,
                    connection_id,
                    query_hash,
                    cutoff_date,
                )
                
                if row and row["avg_mean_time"]:
                    return {
                        "mean_time_ms": float(row["avg_mean_time"]),
                        "max_time_ms": float(row["baseline_max_time"] or 0),
                        "avg_calls": int(row["avg_calls"] or 0),
                    }
                
                return None
                
        except Exception as e:
            logger.error(
                f"Failed to get query baseline: {e}",
                extra={"connection_id": connection_id},
                exc_info=True
            )
            return None
    
    async def get_recent_metrics(
        self,
        connection_id: UUID,
        metric_type: str = "query_performance",
        limit: int = 100,
        days: int = 7
    ) -> List[Dict[str, Any]]:
        """
        Get recent metrics of a specific type.
        
        Args:
            connection_id: Database connection ID
            metric_type: Type of metric (query_performance, wait_statistics, etc.)
            limit: Maximum number of records
            days: Number of days to look back
            
        Returns:
            List of metric records
        """
        try:
            pool = self.db.pool
            cutoff_date = datetime.utcnow() - timedelta(days=days)
            
            async with pool.acquire() as conn:
                rows = await conn.fetch(
                    """
                    SELECT *
                    FROM dba_metrics_history
                    WHERE connection_id = $1
                        AND metric_type = $2
                        AND recorded_at >= $3
                    ORDER BY recorded_at DESC
                    LIMIT $4
                    """,
                    connection_id,
                    metric_type,
                    cutoff_date,
                    limit,
                )
                
                return [dict(row) for row in rows]
                
        except Exception as e:
            logger.error(
                f"Failed to get recent metrics: {e}",
                extra={"connection_id": connection_id},
                exc_info=True
            )
            return []
    
    async def get_capacity_trend(
        self,
        connection_id: UUID,
        days: int = 30
    ) -> List[Dict[str, Any]]:
        """
        Get capacity usage trend over time.
        
        Args:
            connection_id: Database connection ID
            days: Number of days to look back
            
        Returns:
            List of (date, size_mb) tuples
        """
        try:
            pool = self.db.pool
            cutoff_date = datetime.utcnow() - timedelta(days=days)
            
            async with pool.acquire() as conn:
                rows = await conn.fetch(
                    """
                    SELECT 
                        DATE(recorded_at) as metric_date,
                        CAST(metadata->>'size_mb' AS FLOAT) as size_mb
                    FROM dba_metrics_history
                    WHERE connection_id = $1
                        AND metric_type = 'capacity'
                        AND recorded_at >= $2
                    ORDER BY recorded_at
                    """,
                    connection_id,
                    cutoff_date,
                )
                
                return [dict(row) for row in rows]
                
        except Exception as e:
            logger.error(
                f"Failed to get capacity trend: {e}",
                extra={"connection_id": connection_id},
                exc_info=True
            )
            return []
    
    async def cleanup_old_metrics(self, days: int = 90) -> int:
        """
        Clean up old metric records (older than N days).
        
        Args:
            days: Delete records older than this many days
            
        Returns:
            Number of records deleted
        """
        try:
            pool = self.db.pool
            cutoff_date = datetime.utcnow() - timedelta(days=days)
            
            async with pool.acquire() as conn:
                result = await conn.execute(
                    """
                    DELETE FROM dba_metrics_history
                    WHERE recorded_at < $1
                    """,
                    cutoff_date,
                )
                
                deleted = int(result.split()[-1]) if result else 0
                logger.info(
                    f"Cleaned up {deleted} old metric records",
                    extra={"cutoff_date": cutoff_date}
                )
                
                return deleted
                
        except Exception as e:
            logger.error(
                f"Failed to cleanup old metrics: {e}",
                exc_info=True
            )
            return 0


# Global instance
dba_metrics_history_service = DBAMetricsHistoryService()
