"""
Audit Log Service - Log config changes for audit trail
"""
import json
from typing import Optional, Dict, Any
from uuid import UUID
from datetime import datetime

from ...shared.logger import logger
from ...infrastructure.database_client import database_client


class AuditLogService:
    """Service for logging config changes"""
    
    def __init__(self):
        self.db = database_client
    
    def _calculate_diff(self, old_value: Dict[str, Any], new_value: Dict[str, Any]) -> Dict[str, Any]:
        """Calculate diff between old and new values"""
        diff = {}
        
        # Get all keys from both dicts
        all_keys = set(old_value.keys()) | set(new_value.keys())
        
        for key in all_keys:
            old_val = old_value.get(key)
            new_val = new_value.get(key)
            
            # Skip if values are the same
            if old_val == new_val:
                continue
            
            # Handle JSON fields (they might be strings or dicts)
            if isinstance(old_val, str):
                try:
                    old_val = json.loads(old_val)
                except (json.JSONDecodeError, TypeError):
                    pass
            
            if isinstance(new_val, str):
                try:
                    new_val = json.loads(new_val)
                except (json.JSONDecodeError, TypeError):
                    pass
            
            diff[key] = {
                "old": old_val,
                "new": new_val,
            }
        
        return diff
    
    def _serialize_value(self, value: Any) -> Dict[str, Any]:
        """Serialize value to JSON-serializable dict"""
        if value is None:
            return None
        
        if isinstance(value, dict):
            return {k: self._serialize_value(v) for k, v in value.items()}
        elif isinstance(value, list):
            return [self._serialize_value(item) for item in value]
        elif isinstance(value, (str, int, float, bool)):
            return value
        elif isinstance(value, UUID):
            return str(value)
        elif isinstance(value, datetime):
            return value.isoformat()
        else:
            # Try to convert to dict if it has dict() method
            try:
                if hasattr(value, 'dict'):
                    return value.dict()
                elif hasattr(value, '__dict__'):
                    return {k: self._serialize_value(v) for k, v in value.__dict__.items()}
            except Exception:
                pass
            
            # Fallback to string representation
            return str(value)
    
    async def log_config_change(
        self,
        config_type: str,  # 'pattern_rule' | 'keyword_hint' | 'routing_rule' | ...
        config_id: UUID,
        config_name: Optional[str],
        action: str,  # 'create' | 'update' | 'delete' | 'enable' | 'disable'
        changed_by: UUID,
        changed_by_email: Optional[str] = None,
        old_value: Optional[Dict[str, Any]] = None,
        new_value: Optional[Dict[str, Any]] = None,
        tenant_id: Optional[UUID] = None,
        reason: Optional[str] = None,
    ):
        """Log a config change"""
        pool = self.db.pool
        
        # Serialize values
        old_value_json = json.dumps(self._serialize_value(old_value)) if old_value else None
        new_value_json = json.dumps(self._serialize_value(new_value)) if new_value else None
        
        # Calculate diff if both old and new values exist
        diff_json = None
        if old_value and new_value:
            diff = self._calculate_diff(old_value, new_value)
            if diff:
                diff_json = json.dumps(diff)
        
        log_id = UUID(int=0)  # Will be generated by DB
        now = datetime.utcnow()
        
        try:
            async with pool.acquire() as conn:
                row = await conn.fetchrow(
                    """
                    INSERT INTO config_audit_logs (
                        id, tenant_id, config_type, config_id, config_name,
                        changed_by, changed_by_email, action,
                        old_value, new_value, diff, changed_at, reason
                    ) VALUES (
                        gen_random_uuid(), $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
                    ) RETURNING id
                    """,
                    tenant_id,
                    config_type,
                    config_id,
                    config_name,
                    changed_by,
                    changed_by_email,
                    action,
                    old_value_json,
                    new_value_json,
                    diff_json,
                    now,
                    reason,
                )
            
            logger.info(
                f"Audit log created: {config_type} {action}",
                extra={
                    "config_type": config_type,
                    "config_id": str(config_id),
                    "action": action,
                    "changed_by": str(changed_by),
                }
            )
            
            return row["id"]
        except Exception as e:
            logger.error(
                f"Failed to create audit log: {e}",
                exc_info=True,
                extra={
                    "config_type": config_type,
                    "config_id": str(config_id),
                    "action": action,
                }
            )
            # Don't raise - audit logging failure shouldn't break the operation
            return None
    
    async def list_audit_logs(
        self,
        tenant_id: Optional[UUID] = None,
        config_type: Optional[str] = None,
        config_id: Optional[UUID] = None,
        changed_by: Optional[UUID] = None,
        start_date: Optional[datetime] = None,
        end_date: Optional[datetime] = None,
        limit: int = 100,
        offset: int = 0,
    ) -> Dict[str, Any]:
        """List audit logs with filters"""
        pool = self.db.pool
        
        query = "SELECT * FROM config_audit_logs WHERE 1=1"
        params = []
        param_idx = 1
        
        if tenant_id:
            query += f" AND (tenant_id = ${param_idx} OR tenant_id IS NULL)"
            params.append(tenant_id)
            param_idx += 1
        
        if config_type:
            query += f" AND config_type = ${param_idx}"
            params.append(config_type)
            param_idx += 1
        
        if config_id:
            query += f" AND config_id = ${param_idx}"
            params.append(config_id)
            param_idx += 1
        
        if changed_by:
            query += f" AND changed_by = ${param_idx}"
            params.append(changed_by)
            param_idx += 1
        
        if start_date:
            query += f" AND changed_at >= ${param_idx}"
            params.append(start_date)
            param_idx += 1
        
        if end_date:
            query += f" AND changed_at <= ${param_idx}"
            params.append(end_date)
            param_idx += 1
        
        # Get total count
        count_query = query.replace("SELECT *", "SELECT COUNT(*)")
        async with pool.acquire() as conn:
            total = await conn.fetchval(count_query, *params)
        
        # Get items
        query += f" ORDER BY changed_at DESC LIMIT ${param_idx} OFFSET ${param_idx + 1}"
        params.extend([limit, offset])
        
        async with pool.acquire() as conn:
            rows = await conn.fetch(query, *params)
        
        items = []
        for row in rows:
            items.append({
                "id": row["id"],
                "tenant_id": row["tenant_id"],
                "config_type": row["config_type"],
                "config_id": row["config_id"],
                "config_name": row["config_name"],
                "changed_by": row["changed_by"],
                "changed_by_email": row["changed_by_email"],
                "action": row["action"],
                "old_value": json.loads(row["old_value"]) if row["old_value"] else None,
                "new_value": json.loads(row["new_value"]) if row["new_value"] else None,
                "diff": json.loads(row["diff"]) if row["diff"] else None,
                "changed_at": row["changed_at"],
                "reason": row["reason"],
            })
        
        return {
            "items": items,
            "total": total,
            "limit": limit,
            "offset": offset,
        }


# Global audit log service instance
audit_log_service = AuditLogService()

