from logging.config import fileConfig
from sqlalchemy import engine_from_config
from sqlalchemy import pool
from sqlalchemy import MetaData
from alembic import context
import os
import sys

# Add the app directory to the Python path
sys.path.append(os.path.dirname(os.path.dirname(__file__)))

# Create a simple MetaData object for Alembic
# Note: This project uses Clean Architecture with domain entities, not ORM models
# Database schema is managed through Alembic migrations (manually written, not autogenerated)
# We use an empty MetaData since we don't have ORM models to reflect
target_metadata = MetaData()

# this is the Alembic Config object, which provides
# access to the values within the .ini file in use.
config = context.config

# Interpret the config file for Python logging.
# This line sets up loggers basically.
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# other values from the config, defined by the needs of env.py,
# can be acquired:
# my_important_option = config.get_main_option("my_important_option")
# ... etc.

def get_url():
    """Get database URL from environment or alembic.ini"""
    # First try environment variable
    database_url = os.getenv("DATABASE_URL")
    if database_url:
        # Convert async URL to sync URL for Alembic
        if database_url.startswith("postgresql+asyncpg://"):
            database_url = database_url.replace("postgresql+asyncpg://", "postgresql://")
        elif database_url.startswith("postgresql+psycopg2://"):
            database_url = database_url.replace("postgresql+psycopg2://", "postgresql://")
        return database_url
    
    # Fallback to alembic.ini config
    # This will be read from the config section below
    return None

def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode.

    This configures the context with just a URL
    and not an Engine, though an Engine is acceptable
    here as well.  By skipping the Engine creation
    we don't even need a DBAPI to be available.

    Calls to context.execute() here emit the given string to the
    script output.

    """
    url = get_url()
    # If no URL from environment, use the one from alembic.ini (via config object)
    if url is None:
        url = config.get_main_option("sqlalchemy.url")
        # Convert async URL to sync URL for Alembic
        if url and url.startswith("postgresql+asyncpg://"):
            url = url.replace("postgresql+asyncpg://", "postgresql://")
        elif url and url.startswith("postgresql+psycopg2://"):
            url = url.replace("postgresql+psycopg2://", "postgresql://")
    
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode.

    In this scenario we need to create an Engine
    and associate a connection with the context.

    """
    configuration = config.get_section(config.config_ini_section)
    database_url = get_url()
    
    # If we got a URL from environment, use it (and convert async to sync)
    if database_url:
        # Convert async URL to sync URL for Alembic
        if database_url.startswith("postgresql+asyncpg://"):
            database_url = database_url.replace("postgresql+asyncpg://", "postgresql://")
        elif database_url.startswith("postgresql+psycopg2://"):
            database_url = database_url.replace("postgresql+psycopg2://", "postgresql://")
        configuration["sqlalchemy.url"] = database_url
    # Otherwise, use the URL from alembic.ini (which will be read from configuration)
    # But we still need to convert it from async to sync if present
    elif "sqlalchemy.url" in configuration:
        url = configuration["sqlalchemy.url"]
        if url.startswith("postgresql+asyncpg://"):
            configuration["sqlalchemy.url"] = url.replace("postgresql+asyncpg://", "postgresql://")
        elif url.startswith("postgresql+psycopg2://"):
            configuration["sqlalchemy.url"] = url.replace("postgresql+psycopg2://", "postgresql://")
    
    connectable = engine_from_config(
        configuration,
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(
            connection=connection, target_metadata=target_metadata
        )

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
